import { Exo_2 } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Title from "@/components/Title";

export const metadata = {
  title: "Absolute Weeb Reviews",
  description: "Generated by create next app",
};

const exo = Exo_2({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={exo.className}>
      <body>
        <Title />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
